# Generated by Django 5.0.7 on 2024-07-28 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("is_subscribed", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 7, 28, 12, 49, 23, 690840)
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 7, 28, 12, 49, 23, 690840)
                    ),
                ),
            ],
        ),
    ]
