# Generated by Django 5.0.7 on 2024-07-30 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "newsletter",
            "0011_alter_newsletter_created_at_alter_newsletter_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 30, 16, 53, 38, 825788, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 30, 16, 53, 38, 825788, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
