# Generated by Django 5.0.7 on 2024-07-30 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="updated_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
