# Generated by Django 5.0.7 on 2024-07-30 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogpost_created_at_blogpost_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 30, 17, 12, 21, 710411, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 30, 17, 12, 21, 710411, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
