# Generated by Django 5.0.7 on 2024-07-31 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 31, 16, 16, 11, 100339, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 7, 31, 16, 16, 11, 100339, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
