# Generated by Django 5.0.7 on 2024-08-01 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testimonials", "0010_alter_testimonial_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 1, 12, 27, 29, 752149, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 1, 12, 27, 29, 752149, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
